const dataBrand=[
    {
        "brand_name":"LG",
        "isActive": false,
        "brand_id":"lg"
    },
    {
        "brand_name":"Daikin",
        "isActive": false,
        "brand_id":"dk"
    },
    {
        "brand_name":"Tosiba",
        "isActive": false,
        "brand_id":"tb"
    },
    {
        "brand_name":"Aqua",
        "isActive": false,
        "brand_id":"aq"
    },
    {
        "brand_name":"Emerson",
        "isActive": false,
        "brand_id":"em"
    },
    {
        "brand_name":"Keystone",
        "isActive": false,
        "brand_id":"kt"
    },
    {
        "brand_name":"Panasonic",
        "isActive": false,
        "brand_id":"pn"
    },
    {
        "brand_name":"Mitsubishi",
        "isActive": false,
        "brand_id":"ms"
    },
    {
        "brand_name":"Midea",
        "isActive": false,
        "brand_id":"mi"
    },
    {
        "brand_name":"Frigidaire",
        "isActive": false,
        "brand_id":"fr"
    },

]
const dataType = [
    {
        "Type_name":"windowac",
        "isActive": false,
        "type_id":"wac"
    },
    {
        "Type_name":"casseteac",
        "isActive": false,
        "type_id":"cac"
    },
    {
        "Type_name":"splitac",
        "isActive": false,
        "type_id":"sac"
    },
]
const dataProduct=[
    {
        "name":"Aqua Inverter 1 HP AQA-KCRV10NB",
        "img": "./img/máy lạnh aqua/Máy lạnh Aqua Inverter 1 HP AQA-KCRV10NB.jpg",
        "des": "des 1",
        "brand_id": "aq",
        "type_id":"sac",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "1",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 9,200 BTUs",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"PID Inverter",
        "Rapid_cooling":"Turbo",
        "Utilities":"Fan Only mode - only cooling, not cooling Night mode to avoid freezing Dehumidification function BlueFin outdoor/cooling unit to limit corrosion Super quiet operation Quiet Timer on/off Remote lock Screen control temperature display on the indoor unit Cool breeze blowing (for children, the elderly) Auto-restart when power is on Self-cleaning indoor unit Aqua Fresh",
        "Power_consumption":"0.78 kW/h 5 stars (Energy Efficiency 5.46)",
        "Cooler":"Length 85.5 cm - Height 28 cm - Thickness 21 cm - Weight 10 kg",
        "Outdoor":"Length 84 cm - Height 54.5 cm - Thickness 27.7 cm - Weight 25.5 kg",
    },
    {
        "name": "Aqua Inverter 1 HP AQA-RUV10RB",
        "img": "./img/máy lạnh aqua/Máy lạnh Aqua Inverter 1 HP AQA-RUV10RB.jpg",
        "des": "des 2",
        "brand_id": "aq",
        "type_id":"sac",
        "price": '2$',
        "isNew": true,
        "bestSeller":false,
        "id": "2",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 9,500 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"PM 2.5 Filter UVC Pro . Technology","Rapid_cooling":"Eco Inverter",
        "Rapid_cooling":"Turbo",
        "Utilities":"Health Air Flow mode Dehumidification function Self-diagnosis function Indoor unit self-cleaning technology Self Clean Indoor unit temperature display Sleep Mode Auto restart when power is on",
        "Power_consumption":"0.78 kW/h 5 stars (Energy Efficiency 4.76)",
        "Cooler":"Length 80.5 cm - Height 29.2 cm - Thickness 20 cm - Weight 8.4 kg",
        "Outdoor":"Length 77.8 cm - Height 43.5 cm - Thickness 26 cm - Weight 18.5 kg",
    },
    {
        "name": "Aqua Inverter 1 HP AQA-RV9QC",
        "img": "./img/máy lạnh aqua/Máy lạnh Aqua Inverter 1 HP AQA-RV9QC.jpg",
        "des": "des 3",
        "type_id":"sac",
        "brand_id": "aq",
        "price": '3$',
        "isNew": true,
        "bestSeller": false,
        "id": "3",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 9,000 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"Inverter",
        "Rapid_cooling":"Turbo",
        "Utilities":"Dehumidification function Self-diagnosis function Indoor unit self-cleaning technology Self Clean indoor unit temperature display Sleep Mode Auto restart when power is on",
        "Power_consumption":"0.87 kW/h 5 stars (Energy Efficiency 4.54)",
        "Cooler":"Length 70 cm - Height 26.5 cm - Thickness 19 cm - Weight 7.3 kg",
        "Outdoor":"Length 77 cm - Height 43.5 cm - Thickness 26 cm - Weight 18.5 kg",
    },
    {
        "name": "Aqua Inverter 2 HP AQA-RV18QA",
        "img": "./img/máy lạnh aqua/Máy lạnh Aqua Inverter 2 HP AQA-RV18QA.jpg",
        "des": "des 4",
        "type_id":"sac",
        "brand_id": "aq",
        "price": '4$',
        "isNew": true,
        "bestSeller": true,
        "id": "4",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"2 HP - 18,000 BTU",
        "Effective_cooling_range":"From 20 - 30m² (from 60 to 80m³)",
        "Energy_saving_technology":"Eco Inverter",
        "Rapid_cooling":"Turbo",
        "Utilities":"Dehumidification function Self-diagnosis function Indoor unit self-cleaning technology Self Clean indoor unit temperature display Sleep Mode Auto restart when power is on",
        "Power_consumption":"1.6 kW/h 5 stars (Energy Efficiency 5.19)",
        "Cooler":"Length 87.5 cm - Height 30.7 cm - Thickness 21.7 cm - Weight 11 kg",
        "Outdoor":"Length 87 cm - Height 55.3 cm - Thickness 31.5 cm - Weight 30 kg",
    },
    {
        "name": "Daikin Inverter 1.5 HP FTHF35VAVMV",
        "img": "./img/máy lạnh daikin/Máy lạnh 2 chiều Daikin Inverter 1.5 HP FTHF35VAVMV.jpg",
        "des": "des 5",
        "type_id":"sac",
        "brand_id": "dk",
        "price": '5$',
        "isNew": true,
        "bestSeller": false,
        "id": "5",
        "machine_type":"2-way (with heating) With inverter", 
        "Cooling_capacity":"1.5 HP - 11,900 BTU",
        "Effective_cooling_range":"From 15 - 20m² (from 40 to 60 m)",
        "Energy_saving_technology":"Econo Inverter Smart Eye",
        "Rapid_cooling":"Powerful",
        "Utilities":"Pleasant cooling mode Mold Proof function Mold Proof Outdoor unit is equipped with extra circuitry to protect against voltage changes On-off timer Comfortable airflow Coanda Removable water trough (easy to clean unit) Refrigeration) Remote with LED light Optional Daikin Mobile wireless controller Auto-restart when power is restored Auto-heating according to room temperature",
        "Power_consumption":"0.98 kW/h 5 stars (Energy Efficiency 5.50)",
        "Cooler":"Length 77 cm - Height 28.5 cm - Thickness 24.2 cm - Weight 9 kg",
        "Outdoor":"Length 67.5 cm - Height 55 cm - Thickness 28.4 cm - Weight 26 kg",
    },
    {
        "name": "Daikin Inverter 1 HP ATKF25XVMV",
        "img": "./img/máy lạnh daikin/Máy lạnh Daikin Inverter 1 HP ATKF25XVMV.jpg",
        "des": "des 6",
        "type_id":"sac",
        "brand_id": "dk",
        "price": '6$',
        "isNew": true,
        "bestSeller": true,
        "id": "6",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 9,200 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"Inverter",
        "Rapid_cooling":"Powerful",
        "Utilities":"Anti-mildew function protects health Super quiet operation Quiet Timer on/off Comfortable airflow Coanda Optional purchase of Daikin Mobile wireless controller Auto restart when power is on",
        "Power_consumption":"0.82 kWh (when operating 8 hours continuously) 5 stars (Energy efficiency 5.21)",
        "Cooler":"Length 77 cm - Height 28.6 cm - Thickness 24.4 cm - Weight 9 kg",
        "Outdoor":"Length 75.6 cm - Height 41.8 cm - Thickness 26.2 cm - Weight 19 kg",
    },
    {
        "name": "Daikin Inverter 1 HP FTKB25WMVMV",
        "img": "./img/máy lạnh daikin/Máy lạnh Daikin Inverter 1 HP FTKB25WMVMV.jpg",
        "des": "des 7",
        "type_id":"sac",
        "brand_id": "dk",
        "price": '7$',
        "isNew": true,
        "bestSeller": false,
        "id": "7",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 8,500 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"Econo Inverter",
        "Rapid_cooling":"Powerful",
        "Utilities":"Anti-mildew function to protect health Dehumidification function Super quiet operation Quiet Timer on/off Comfortable airflow Coanda Auto restart when power is on",
        "Power_consumption":"0.82 kWh (when operating 8 hours continuously) 5 stars (5.23 Energy Efficiency)",
        "Cooler":"Length 77 cm - Height 28.5 cm - Thickness 24.2 cm - Weight 8 kg",
        "Outdoor":"Length 74.5 cm - Height 41.8 cm - Thickness 27 cm - Weight 19 kg",
    },
    {
        "name": "Daikin Inverter 1 HP FTKY25WMVMV",
        "img": "./img/máy lạnh daikin/Máy lạnh Daikin Inverter 1 HP FTKY25WMVMV.jpg",
        "des": "des 8",
        "type_id":"sac",
        "brand_id": "dk",
        "price": '8$',
        "isNew": true,
        "bestSeller": true,
        "id": "8",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 9,200 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"Inverter Smart Eye",
        "Rapid_cooling":"Powerful",
        "Utilities":"Anti-mold function combined with Streamer technology Humidity Sensor Ultra-quiet operation Quiet Timer on/off Comfortable airflow Coanda 3D Optional purchase of Daikin Mobile wireless controller Auto restart when power is on",
        "Power_consumption":"0.7 kW/h 5 stars (Energy Efficiency 6.28)",
        "Cooler":"Length 83.5 cm - Height 28.5 cm - Thickness 24 cm - Weight 11 kg",
        "Outdoor":"Length 75 cm - Height 55 cm - Thickness 30 cm - Weight 22 kg",
    },
    {
        "name": "Daikin Inverter 1.5 HP ATKF35XVMV",
        "img": "./img/máy lạnh daikin/Máy lạnh Daikin Inverter 1.5 HP ATKF35XVMV.jpg",
        "des": "des 9",
        "type_id":"sac",
        "brand_id": "dk",
        "price": '9$',
        "isNew": true,
        "bestSeller": true,
        "id": "9",
        "machine_type":"1-way air conditioner(cooling only)", 
        "Cooling_capacity":"1.5 HP - 12,300 BTU",
        "Effective_cooling_range":"From 15 - 20m² (from 40 to 60 m)",
        "Energy_saving_technology":"Invester",
        "Rapid_cooling":"Powerful",
        "Utilities":"Anti-mold function to protect health-Comfortable airflow Coanda-Quiet operation Quiet-Timer to turn on and off-Auto-restart when power is on-Optional purchase of Daikin Mobile wireless controlle",
        "Power_consumption":"1.26 kW/h",
        "Cooler":"Length 77 cm - Height 28.6 cm - Thickness 24.4 cm - Weight 8 kg",
        "Outdoor":"Length 67.5 cm - Height 55 cm - Thickness 28.4 cm - Weight 22 kg",
    },
    {
        "name": "LG Inverter 1 HP V10API1",
        "img": "./img/máy lạnh LG/Máy lạnh LG Inverter 1 HP V10API1.jpg",
        "des": "des 10",
        "type_id":"sac",
        "brand_id": "lg",
        "price": '10$',
        "isNew": true,
        "bestSeller": false,
        "id": "10",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 9,200 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"Dual inverter Energy Ctrl - 4-level active energy control",
        "Rapid_cooling":"Jet Cool",
        "Utilities":"Fault self - diagnostic function Self - cleaning function Night mode to avoid frost ) Generates ions to purify the air Auto-restart when power is on. Control by phone, with wifi 4-way air-swing to help spread cold air evenly",
        "Power_consumption":"0.77 kW/h 5 stars (Energy Efficiency 5.42)",
        "Cooler":"Length 83.7 cm - Height 30.8 cm - Thickness 18.9 cm - Weight 8.2 kg",
        "Outdoor":"Length 82.2 cm - Height 50 cm - Thickness 25.7 cm - Weight 21.7 kg",
    },
    {
        "name": "LG Inverter 1 HP V10WIN",
        "img": "./img/máy lạnh LG/Máy lạnh LG Inverter 1 HP V10WIN.jpg",
        "des": "des 11",
        "type_id":"sac",
        "brand_id": "lg",
        "price": '11$',
        "isNew": true,
        "bestSeller": true,
        "id": "11",
        "machine_type":"1-way air conditioner (cooling only)", 
        "Cooling_capacity":"1 HP - 8,800 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"Dual inverter Energy Ctrl - 4-level active energy control",
        "Rapid_cooling":"Jet Cool",
        "Utilities":"Night mode to avoid freezing-Fault self-diagnosis function-Anti-corrosion Gold-Fi technology-Timer on, off-Pleasant wind blowing (for children, the elderly)-Auto-restart when power is on-Self-cleaning function",
        "Power_consumption":"0.92 kW/h",
        "Cooler":"Length 75.6 cm - Height 26.5 cm - Thickness 18.4 cm - Weight 7.4 kg",
        "Outdoor":"Length 80.4 cm - Height 49.5 cm - Thickness 26.5 cm - Weight 20 kg",
    },
    {
        "name": "LG Inverter 1.5 HP V13APFP",
        "img": "./img/máy lạnh LG/Máy lạnh LG Inverter 1.5 HP V13APFP.jpg",
        "des": "des 12",
        "type_id":"sac",
        "brand_id": "lg",
        "price": '12$',
        "isNew": true,
        "bestSeller": false,
        "id": "12",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1.5 HP - 12,000 BTU",
        "Effective_cooling_range":"From 15 - 20m² (from 40 to 60 m)",
        "Energy_saving_technology":"Dual inverter Energy Ctrl - 4-level active energy control",
        "Rapid_cooling":"Jet Cool",
        "Utilities":"Night mode to avoid frost Self-diagnostic function Self-cleaning function Anti-corrosion Gold-Fin technology Timer on and off Time display on the indoor unit Cool breeze blowing (for children, the elderly) ) Auto-restart when power is on. Control by phone, with wifi",
        "Power_consumption":"1.09 kW/h 5 stars (Energy Efficiency 5.14)",
        "Cooler":"Length 85.7 cm - Height 34.8 cm - Thickness 19 cm - Weight 9.6 kg",
        "Outdoor":"Length 71.7 cm - Height 49.5 cm - Thickness 19 cm - Weight 23 kg",
    },
    {
        "name": "LG Inverter 1.5 HP V13API1",
        "img": "./img/máy lạnh LG/Máy lạnh LG Inverter 1.5 HP V13API1.jpg",
        "des": "des 13",
        "type_id":"sac",
        "brand_id": "lg",
        "price": '130$',
        "isNew": true,
        "bestSeller": true,
        "id": "13",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1.5 HP - 12,000 BTU",
        "Effective_cooling_range":"From 15 - 20m² (from 40 to 60 m)",
        "Energy_saving_technology":"Dual inverter Energy Ctrl - 4-level active energy control",
        "Rapid_cooling":"Jet Cool",
        "Utilities":"Fault self - diagnostic function Self - cleaning function Night mode to avoid frost ) Generates ions to purify the air Auto-restart when power is on. Control by phone, with wifi 4-way air-swing to help spread cold air evenly",
        "Power_consumption":"1.03 kW/h 5 stars (Energy Efficiency 5.29)",
        "Cooler":"Length 83.7 cm - Height 31.7 cm - Thickness 18.9 cm - Weight 8.2 kg",
        "Outdoor":"Length 80.8 cm - Height 50 cm - Thickness 25 cm - Weight 23 kg",
    },
    {
        "name": "LG Inverter 1.5 HP V13WIN",
        "img": "./img/máy lạnh LG/Máy lạnh LG Inverter 1.5 HP V13WIN.jpg",
        "des": "des 14",
        "type_id":"sac",
        "brand_id": "lg",
        "price": '130$',
        "isNew": true,
        "bestSeller": true,
        "id": "14",
        "machine_type":"1-way air conditioner (cooling only)", 
        "Cooling_capacity":"1.5 HP - 11,000 BTU",
        "Effective_cooling_range":"From 15 - 20m² (from 40 to 60 m)",
        "Energy_saving_technology":"Dual inverter, Energy Ctrl - 4-level active energy control",
        "Rapid_cooling":"Jet Cool",
        "Utilities":"Night mode to avoid freezing-Fault self-diagnosis function-Anti-corrosion Gold-Fi technology-Timer on, off-Pleasant wind blowing (for children, the elderly)-Auto-restart when power is on-Self-cleaning function",
        "Power_consumption":"1.15 kW/h",
        "Cooler":"Length 83.7 cm - Height 30.8 cm - Thickness 18.9 cm - Weight 8.2 kg",
        "Outdoor":"Length 71.7 cm - Height 49.5 cm - Thickness 23 cm - Weight 22.1 kg",
    },
    {
        "name": "Toshiba 1 HP Inverter RAS-H10C4KCVG-V",
        "img": "./img/máy lạnh toshiba/Máy lạnh Toshiba 1 HP Inverter RAS-H10C4KCVG-V.jpg",
        "des": "des 15",
        "brand_id": "tb",
        "type_id":"sac",
        "price": '130$',
        "isNew": true,
        "bestSeller": false,
        "id": "15",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 9,000 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"Eco Hybrid Inverter",
        "Rapid_cooling":"Hi Power",
        "Utilities":"Fan Only mode - cooling only, no cooling Dehumidification function Self cleaning function Shutdown timer Auto restart when power is on",
        "Power_consumption":"0.9 kW/h 5 stars (Energy Efficiency 4.34)",
        "Cooler":"Length 77 cm - Height 25.5 cm - Thickness 22 cm - Weight 9 kg",
        "Outdoor":"Length 65.5 cm - Height 53 cm - Thickness 21 cm - Weight 17 kg",
    },
    {
        "name": "Toshiba 1.5 HP Inverter RAS-H13C4KCVG-V",
        "img": "./img/máy lạnh toshiba/Máy lạnh Toshiba 1.5 HP Inverter RAS-H13C4KCVG-V.jpg",
        "des": "des 16",
        "type_id":"sac",
        "brand_id": "tb",
        "price": '130$',
        "isNew": true,
        "bestSeller": true,
        "id": "16",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1.5 HP - 12,000 BTU",
        "Effective_cooling_range":"From 15 - 20m² (from 40 to 60 m)",
        "Energy_saving_technology":"Eco Hybrid Inverter",
        "Rapid_cooling":"Hi Power",
        "Utilities":"Fan Only mode - cooling only, no cooling Dehumidification function Self cleaning function Shutdown timer Auto restart when power is on",
        "Power_consumption":"1.18 kW/h 5 stars (Energy Efficiency 4.62)",
        "Cooler":"Length 77 cm - Height 25.5 cm - Thickness 22 cm - Weight 9 kg",
        "Outdoor":"Length 65.5 cm - Height 53 cm - Thickness 21 cm - Weight 21 kg",
    },
    {
        "name": "Toshiba 2 HP Inverter RAS-H18C4KCVG-V",
        "img": "./img/máy lạnh toshiba/Máy lạnh Toshiba 2 HP Inverter RAS-H18C4KCVG-V.jpg",
        "des": "des 17",
        "type_id":"sac",
        "brand_id": "tb",
        "price": '130$',
        "isNew": true,
        "bestSeller": false,
        "id": "17",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"2 HP - 17,000 BTU",
        "Effective_cooling_range":"From 20 - 30m² (from 60 to 80m³)",
        "Energy_saving_technology":"Eco Hybrid Inverter",
        "Rapid_cooling":"Hi Power",
        "Utilities":"Fan Only mode - cooling only, no cooling Dehumidification function Self cleaning function Shutdown timer Auto restart when power is on",
        "Power_consumption":"1.66 kW/h 5 stars (Energy Efficiency 4.84)",
        "Cooler":"Length 80 cm - Height 29 cm - Thickness 24 cm - Weight 9 kg",
        "Outdoor":"Length 84.5 cm - Height 55 cm - Thickness 31.6 cm - Weight 33 kg",
    },
    {
        "name": "Toshiba Inverter 1 HP RAS-H10E2KCVG-V",
        "img": "./img/máy lạnh toshiba/Máy lạnh Toshiba Inverter 1 HP RAS-H10E2KCVG-V.jpg",
        "des": "des 18",
        "type_id":"sac",
        "brand_id": "tb",
        "price": '130$',
        "isNew": true,
        "bestSeller": false,
        "id": "18",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 9,000 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"Eco Hybrid Inverter",
        "Rapid_cooling":"Hi Power",
        "Utilities":"Fan Only mode - cooling only, no cooling Dehumidification function Comfort Sleep function Comfort Sleep Self-diagnostic function Self-cleaning function Memorize preferred cooling mode Ultra-quiet operation Quiet Timer to turn on and off the machine Pleasant airflow protects the skin Hada Care Creates air-purifying ions Automatically restarts when power is on",
        "Power_consumption":"0.76 kW/h 5 stars (Energy Efficiency 5.04)",
        "Cooler":"Length 80 cm - Height 29.3 cm - Thickness 22.6 cm - Weight 9 kg",
        "Outdoor":"Length 65.5 cm - Height 53 cm - Thickness 21.5 cm - Weight 18 kg",
    },
    {
        "name": "Toshiba Inverter 1 HP RAS-H10Z1KCVG-V",
        "img": "./img/máy lạnh toshiba/Máy lạnh Toshiba Inverter 1 HP RAS-H10Z1KCVG-V.jpg",
        "des": "des 19",
        "type_id":"sac",
        "brand_id": "tb",
        "price": '130$',
        "isNew": true,
        "bestSeller": false,
        "id": "19",
        "machine_type":"1 way (cooling only) With Inverter", 
        "Cooling_capacity":"1 HP - 9,000 BTU",
        "Effective_cooling_range":"Under 15m² (from 30 to 45m³)",
        "Energy_saving_technology":"Eco Hybrid, Inverter",
        "Rapid_cooling":"Hi Power",
        "Utilities":"Fan Only mode - only cooling, not cooling Dehumidifying function Timer on and off Auto restart when power is on",
        "Power_consumption":"0.9 kW/h, 5 stars (Energy Efficiency 4.33)",
        "Cooler":"Length 77 cm - Height 28.8 cm - Thickness 22.5 cm - Weight 9 kg",
        "Outdoor":"Length 66.5 cm - Height 53 cm - Thickness 21.5 cm - Weight 17 kg",
    },
    {
        "name": "Emerson Quiet Kool 15,000 BTU Energy Star Smart Window Air Conditioner",
        "img": "./img/window ac/Emerson Quiet Kool 15,000 BTU Energy Star Smart Window Air Conditioner.jpg",
        "des": "des 20",
        "type_id":"wac",
        "brand_id": "em",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "20",
        "machine_type":"Smart window air conditioner", 
        "Cooling_capacity":"15,000 BTU/hour",
        "Effective_cooling_range":"Effective cooling range of up to 700 square feet",
        "Energy_saving_technology":"Smart energy-saving technology",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, quiet mode",
        "Power_consumption":"1,520 W",
        "Cooler":"Air cooling system",
        "Outdoor":"Ability to operate in outdoor environments with temperatures ranging from 60 to 100 degrees F",
    },
    {
        "name": "Keystone 6,000 BTU Energy Star Window Mounted Air Conditioner",
        "img": "./img/window ac/Keystone 6,000 BTU Energy Star Window Mounted Air Conditioner.jpg",
        "des": "des 21",
        "type_id":"wac",
        "brand_id": "kt",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "21",
        "machine_type":"Window mounted air conditioner", 
        "Cooling_capacity":"6,000 BTU/hour",
        "Effective_cooling_range":"Effective cooling range of up to 250 square feet",
        "Energy_saving_technology":"Energy-saving mode",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, sleep mode",
        "Power_consumption":"520 W",
        "Cooler":"Air cooling system",
        "Outdoor":"Ability to operate in outdoor environments with temperatures ranging from 60 to 90 degrees F",
    },
    {
        "name": "LG 6,000 BTU High Efficiency Window AC, Cools 250 Sq.Ft",
        "img": "./img/window ac/LG 6,000 BTU High Efficiency Window AC, Cools 250 Sq.Ft.jpg",
        "des": "des 22",
        "type_id":"wac",
        "brand_id": "lg",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "22",
        "machine_type":"Window air conditioner", 
        "Cooling_capacity":"6,000 BTU/hour",
        "Effective_cooling_range":"Effective cooling range of up to 250 square feet",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, 3 fan speeds",
        "Power_consumption":"500 W",
        "Cooler":"Air cooling system",
        "Outdoor":"Can operate in outdoor environments with temperatures ranging from 60 to 86 degrees F",
    },
    {
        "name": "LG 7,500 BTU Window Air Conditioner with Supplemental Heat",
        "img": "./img/window ac/LG 7,500 BTU Window Air Conditioner with Supplemental Heat.jpg",
        "des": "des 23",
        "type_id":"wac",
        "brand_id": "lg",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "23",
        "machine_type":"Window air conditioner with supplemental heat", 
        "Cooling_capacity":"7,500 BTU/hour",
        "Effective_cooling_range":"Effective cooling range of up to 320 square feet",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"620 W",
        "Cooler":"Air cooling system",
        "Outdoor":"Can operate in outdoor environments with temperatures ranging from 60 to 86 degrees F",
    },
    {
        "name": "Daikin ceiling mounted air conditioner (5.5Hp) FCC140AV1V - 3 phase Ion-Plasma air purifier",
        "img": "./img/cassete ac/daikin/Daikin ceiling mounted air conditioner (5.5Hp) FCC140AV1V - 3 phase Ion-Plasma air purifier.webp",
        "des": "des 24",
        "type_id":"cac",
        "brand_id": "dk",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "24",
        "machine_type":"Mono - 1-way type (cooling only)", 
        "Cooling_capacity":"5.5 Hp - 48,000 Btu/h - 14.07 kW",
        "Effective_cooling_range":"Area 75 - 85 m² or 230 - 250 m³ (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"",
        "Power_consumption":"4.1 kW",
        "Cooler":"25 Kg",
        "Outdoor":"84 Kg",
    },
    {
        "name": "LG Ceiling Cassette Air Conditioner inverter (2.5Hp) ZTNQ24GTLA0 - Gas R32",
        "img": "./img/cassete ac/lg/LG Ceiling Cassette Air Conditioner inverter (2.5Hp) ZTNQ24GTLA0 - Gas R32.webp",
        "des": "des 25",
        "type_id":"cac",
        "brand_id": "lg",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "25",
        "machine_type":"Inverter - 1 way type (cooling only)", 
        "Cooling_capacity":"2.5 HP - 22.000 Btu/h - 6.45 kW",
        "Effective_cooling_range":"Area 31 - 34 m² or 93 - 102 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"2.19 kW",
        "Cooler":"14.5 Kg",
        "Outdoor":"41.5 Kg",
    },
    {
        "name": "Mitsubishi Heavy ceiling cassette air conditioner inverter (2.5Hp) FDT60YA-W5 model 2022",
        "img": "./img/cassete ac/mitsubishi/Mitsubishi Heavy ceiling cassette air conditioner inverter (2.5Hp) FDT60YA-W5 model 2022.webp",
        "des": "des 26",
        "type_id":"cac",
        "brand_id": "ms",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "26",
        "machine_type":"With Inverter - DC type (cooling only)", 
        "Cooling_capacity":"2.5 HP (2.5Hp) - 6.1 kW",
        "Effective_cooling_range":"Area of ​​35 - 40 m² or 108 - 120 m of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"1.72 kW/h",
        "Cooler":"19 Kg",
        "Outdoor":"32 Kg",
    },
    {
        "name": "Panasonic ceiling mounted air conditioning inverter 6.0Hp S-3448PU3H - 3 phases",
        "img": "./img/cassete ac/panasonic/Panasonic ceiling mounted air conditioning inverter 6.0Hp S-3448PU3H - 3 phases.webp",
        "des": "des 27",
        "type_id":"cac",
        "brand_id": "pn",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "27",
        "machine_type":"Inverter - 1-way type (cooling only)", 
        "Cooling_capacity":"6.0 Hp - 47,800 Btu/h - 14.0 kW",
        "Effective_cooling_range":"Area of 77 - 80 m² or 231 - 240 m³ (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"4.83 kW",
        "Cooler":"24 Kg",
        "Outdoor":"67 Kg",
    },
    {
        "name": "Toshiba Ceiling Cassette Air Conditioner inverter (6.0Hp) RAV-GV4801A8P-V - 3 phase",
        "img": "./img/cassete ac/toshiba/Toshiba Ceiling Cassette Air Conditioner inverter (6.0Hp) RAV-GV4801A8P-V - 3 phase.webp",
        "des": "des 28",
        "type_id":"cac",
        "brand_id": "tb",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "28",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "LG 24,500 BTU Window Air Conditioner, Cools 1,560 Sq.Ft",
        "img": "./img/window ac/LG 24,500 BTU Window Air Conditioner, Cools 1,560 Sq.Ft (new).jpg",
        "des": "des 29",
        "type_id":"wac",
        "brand_id": "lg",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "29",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "LG 9,800 BTU Through-the-Wall Air Conditioner, Cools 450 Sq.Ft",
        "img": "./img/window ac/LG 9,800 BTU Through-the-Wall Air Conditioner, Cools 450 Sq.Ft (new).webp",
        "des": "des 30",
        "type_id":"wac",
        "brand_id": "lg",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "30",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Emerson Quiet Kool 12,000 BTU 230V",
        "img": "./img/window ac/Emerson Quiet Kool 12,000 BTU 230V (new).jpg",
        "des": "des 31",
        "type_id":"wac",
        "brand_id": "em",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "31",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Keystone 10,000 BTU Energy Star Window Mounted Air Conditioner",
        "img": "./img/window ac/Keystone 10,000 BTU Energy Star Window Mounted Air Conditioner (new).jpg",
        "des": "des 32",
        "type_id":"wac",
        "brand_id": "kt",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "32",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Midea 5,000 BTU EasyCool Window Air Conditioner",
        "img": "./img/window ac/Midea 5,000 BTU EasyCool Window Air Conditioner.jpg",
        "des": "des 33",
        "type_id":"wac",
        "brand_id": "mi",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "33",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Midea 8,000 BTU U-Shaped Smart Inverter Window Air Conditioner",
        "img": "./img/window ac/Midea 8,000 BTU U-Shaped Smart Inverter Window Air Conditioner.jpg",
        "des": "des 34",
        "type_id":"wac",
        "brand_id": "mi",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "34",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Frigidaire FFRE083WAE Window Air Conditioner, 8,000 BTU, White",
        "img": "./img/window ac/Frigidaire FFRE083WAE Window Air Conditioner, 8,000 BTU, White.jpg",
        "des": "des 35",
        "type_id":"wac",
        "brand_id": "fr",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "35",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Frigidaire 12,000 BTU Connected Window-Mounted Room Air Conditioner",
        "img": "./img/window ac/Frigidaire 12,000 BTU Connected Window-Mounted Room Air Conditioner.jpg",
        "des": "des 36",
        "type_id":"wac",
        "brand_id": "fr",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "36",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Daikin Ceiling Cassette AC FCFC40DVM (1.5Hp)",
        "img": "./img/cassete ac/daikin/Daikin Ceiling Cassette AC FCFC40DVM (1.5Hp) (1).webp",
        "des": "des 37",
        "type_id":"cac",
        "brand_id": "dk",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "37",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "LG Round Cassette air cooling Inverter (5.0Hp) ZTNQ48GYLA0 - Gas R32",
        "img": "./img/cassete ac/lg/LG Round Cassette air cooling Inverter (5.0Hp) ZTNQ48GYLA0 - Gas R32 (1).webp",
        "des": "des 38",
        "type_id":"cac",
        "brand_id": "lg",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "38",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Midea Inverter Ceiling Air Conditioner 2.5 HP (2.5 Horses) MCD1-24HRDN1 model 2022",
        "img": "./img/cassete ac/midea/Midea Inverter Ceiling Air Conditioner 2.5 HP (2.5 Horses) MCD1-24HRDN1 model 2022.webp",
        "des": "des 39",
        "type_id":"cac",
        "brand_id": "mi",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "39",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Mitsubishi Heavy ceiling cassette air conditioner Inverter 2.0 HP (2.0 Horsepower) FDTC50VH",
        "img": "./img/cassete ac/mitsubishi/Mitsubishi Heavy ceiling cassette air conditioner Inverter 2.0 HP (2.0 Horsepower) FDTC50VH (1).webp",
        "des": "des 40",
        "type_id":"cac",
        "brand_id": "ms",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "40",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Panasonic Ceiling mounted air conditioning 4.5Hp S-42PU1H5B - 3 Phases",
        "img": "./img/cassete ac/panasonic/Panasonic Ceiling mounted air conditioning 4.5Hp S-42PU1H5B - 3 Phases (1).webp",
        "des": "des 41",
        "type_id":"cac",
        "brand_id": "pn",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "41",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
    {
        "name": "Toshiba Ceiling Cassette Air Conditioner Inverter 3.0 HP (3.0 Horsepower) RAV-GE3001AP-V RAV-GE3001UP-V",
        "img": "./img/cassete ac/toshiba/Toshiba Ceiling Cassette Air Conditioner Inverter 3.0 HP (3.0 Horsepower) RAV-GE3001AP-V RAV-GE3001UP-V (1).webp",
        "des": "des 42",
        "type_id":"cac",
        "brand_id": "tb",
        "price": '1$',
        "isNew": true,
        "bestSeller": false,
        "id": "42",
        "machine_type":"Inverter - 1-way type (only cooling)", 
        "Cooling_capacity":"6.0 HP - 48.000 Btu/h",
        "Effective_cooling_range":"Area 77 - 80 m² or 231 - 240 m³ of gas (suitable for living room, office)",
        "Energy_saving_technology":"Energy-saving mode, with an Energy Star rating",
        "Rapid_cooling":"Rapid cooling capability",
        "Utilities":"Remote control, air filter, multiple fan speeds, supplemental heat option",
        "Power_consumption":"3 Phase, 380 V, 50Hz",
        "Cooler":"RAV-GV4801A8P-V",
        "Outdoor":"RAV-GE4801UP-V",
    },
]